import { useState } from 'react';
import { View, Text, ScrollView, Pressable, RefreshControl } from 'react-native';
import { useApp } from '@/src/app-context';
import { makeStyles, useTheme } from '@/src/theme';
import { api } from '@/src/api';
import { Icon, Card, useTypography, IconButton, Info } from '@/src/components/ui';

export default function Habits() {
  const s = useStyles(); const t = useTypography(); const { colors: c } = useTheme();
  const { data, refresh, refreshing, setPanel, notify } = useApp(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (!data) return null;
  const { log, timeline } = data;
  const water = async (change: number) => { if (busy) return; setBusy(true); try { await api('/logs/today', 'PUT', { water: Math.max(0, Math.min(20, log.water + change)) }); await refresh(); setError(''); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const recover = async () => { if (!log.recovery_mode) { setPanel('recovery'); return; } try { await api('/logs/today', 'PUT', { recovery_mode: false }); await refresh(); notify('Hazır olduğunda, kendi hızında devam.'); } catch (e: any) { setError(e.message); } };
  const dates = Array.from({ length: 7 }, (_, i) => { const date = new Date(`${data.date}T12:00:00`); date.setDate(date.getDate() - 6 + i); return date; });
  return <ScrollView testID="habits-scroll" showsVerticalScrollIndicator={false} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={c.brandPrimary} />}>
    <View style={s.intro}><Text style={t.body}>Her gün aynı olmak zorunda değil.{ '\n' }Devam etmek kadar, dinlenmek de değerli.</Text><Icon name="flower-outline" size={37} color={c.borderStrong} /></View>
    <Card testID="habit-timeline"><View style={t.between}><Text style={t.h3}>Son 7 günün ritmi</Text><Text style={t.small}>Adım adım</Text></View><View style={s.timeline}>{dates.map((date, i) => { const iso = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; const entry = timeline.find(l => l.date === iso); const active = entry && (entry.water > 0 || entry.sleep !== null || entry.overall_score !== null || entry.journal_entry); return <View key={iso} testID={`timeline-day-${iso}`} style={s.day}><Text style={s.dayLabel}>{date.toLocaleDateString('tr-TR', { weekday: 'short' })}</Text><View style={[s.dayCircle, active && s.dayActive, entry?.recovery_mode && s.dayRecovery, i === 6 && s.dayToday]}>{entry?.recovery_mode ? <Icon name="pause" size={15} color={c.onInfo} /> : active ? <Icon name="checkmark" size={15} color={c.brandPrimary} /> : <Text style={s.dayNumber}>{date.getDate()}</Text>}</View></View>; })}</View><View style={s.legend}><View style={s.legendDot} /><Text style={t.small}>Devam</Text><View style={[s.legendDot, { backgroundColor: c.info }]} /><Text style={t.small}>Dinlenme de ritme dahil</Text></View></Card>
    <Card style={s.water} testID="water-habit-card"><View style={t.between}><View style={t.row}><Icon name="water-outline" color={c.onWater} /><Text style={t.h3}>Bir bardak iyi gelir.</Text></View><Text style={t.small}>250 ml</Text></View><Text testID="water-count" style={s.big}>{log.water}<Text style={s.unit}> / 8 bardak</Text></Text><View style={s.drops}>{Array.from({ length: 8 }, (_, i) => <Icon key={i} name={i < log.water ? 'water' : 'water-outline'} size={25} color={i < log.water ? c.onWater : c.borderStrong} />)}</View><View style={t.between}><Text style={t.small}>{(log.water * .25).toLocaleString('tr-TR')} litre kaydettin</Text><View style={t.row}><Pressable disabled={busy || log.water === 0} testID="water-decrease-button" onPress={() => water(-1)} style={({ pressed }) => [s.waterControl, (pressed || busy || log.water === 0) && s.disabled]}><Icon name="remove" size={22} /></Pressable><Pressable disabled={busy || log.water === 20} testID="water-increase-button" onPress={() => water(1)} style={({ pressed }) => [s.waterControl, s.waterAdd, (pressed || busy) && s.disabled]}><Icon name="add" color={c.onBrandPrimary} size={22} /></Pressable></View></View></Card>
    <Pressable testID="sleep-habit-button" onPress={() => setPanel('sleep')} style={({ pressed }) => pressed && s.disabled}><Card style={s.sleep}><View style={t.between}><View style={t.row}><Icon name="moon-outline" color={c.onInfo} /><Text style={t.h3}>Dün gece nasıl uyudun?</Text></View><Icon name="arrow-forward" size={18} /></View><Text testID="sleep-duration" style={s.big}>{log.sleep ?? '—'}<Text style={s.unit}> saat</Text></Text><Text style={t.small}>{log.sleep === null ? 'Uyku süreni ekleyerek bedeninin ritmini tanı.' : 'Uyku kaydını düzenlemek için dokun.'}</Text></Card></Pressable>
    <Pressable testID="recovery-mode-button" onPress={recover} style={({ pressed }) => pressed && s.disabled}><Card style={[s.recovery, log.recovery_mode && s.recoveryActive]}><View style={t.between}><Icon name={log.recovery_mode ? 'play-outline' : 'pause-outline'} color={c.onInfo} /><Text style={s.recoveryBadge}>{log.recovery_mode ? 'DİNLENME AÇIK' : 'KENDİNE ALAN AÇ'}</Text></View><Text style={t.h2}>{log.recovery_mode ? 'Bugün kendine alan açtın.' : 'Bugün biraz yavaşlayalım mı?'}</Text><Text style={t.body}>{log.recovery_mode ? 'Ritmin kesilmedi, sadece rengi değişti. Hazır hissediyorsan devam etmek için dokun.' : 'Dinlenme modunda çizgin kopmaz. Su ve uyku hedefleri bir gün bekleyebilir.'}</Text></Card></Pressable>
    <Card><View style={t.between}><Text style={t.h3}>Kendine bir cümle</Text><IconButton icon="create-outline" onPress={() => setPanel('journal')} testID="journal-edit-button" /></View><Text testID="journal-preview" style={t.body}>{log.journal_entry || 'Bugün neye ihtiyacın var? Birkaç kelime bile yeter.'}</Text></Card>
    <Info text={error} error /><Text style={t.small}>8 bardak su ve 8 saat uyku genel takip referanslarıdır; kişisel gereksinimler değişir. Diyetisyeninle birlikte uyarlayabilirsin.</Text>
  </ScrollView>;
}
const useStyles = makeStyles(c => ({ content: { paddingHorizontal: 24, paddingTop: 6, paddingBottom: 28, gap: 20, width: '100%', maxWidth: 680, alignSelf: 'center' }, intro: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 15 }, timeline: { flexDirection: 'row', justifyContent: 'space-between', gap: 3, marginTop: 9 }, day: { alignItems: 'center', gap: 10, flex: 1 }, dayLabel: { fontSize: 9, color: c.muted }, dayCircle: { width: 32, height: 32, borderRadius: 17, backgroundColor: c.surfaceTertiary, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.transparent }, dayActive: { backgroundColor: c.mint }, dayRecovery: { backgroundColor: c.info }, dayToday: { borderColor: c.brandPrimary }, dayNumber: { color: c.muted, fontSize: 11 }, legend: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10 }, legendDot: { width: 6, height: 6, borderRadius: 4, backgroundColor: c.success }, water: { backgroundColor: c.water, borderColor: c.transparent }, big: { fontSize: 42, color: c.onSurface, fontWeight: '400', letterSpacing: -1.5, marginVertical: 4 }, unit: { fontSize: 14, color: c.onSurfaceTertiary, letterSpacing: 0 }, drops: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, waterControl: { height: 42, width: 42, borderRadius: 23, backgroundColor: c.surfaceSecondary, alignItems: 'center', justifyContent: 'center' }, waterAdd: { backgroundColor: c.brandPrimary }, disabled: { opacity: .5 }, sleep: { backgroundColor: c.lavender, borderColor: c.transparent }, recovery: { backgroundColor: c.surfaceSecondary, borderColor: c.info }, recoveryActive: { backgroundColor: c.lavender }, recoveryBadge: { fontSize: 8, letterSpacing: 1.5, color: c.onInfo, fontWeight: '600' } }));