import { useState } from 'react';
import { View, Text, Pressable, Keyboard } from 'react-native';
import { makeStyles, useTheme } from '@/src/theme';
import { useApp, Panel } from '@/src/app-context';
import { useSession } from '@/src/session';
import { api } from '@/src/api';
import { Sheet, Button, Field, Icon, Card, Info, useTypography } from '@/src/components/ui';

const TITLES: Record<string, string> = { sleep: 'Dinlenmenin ritmi.', recovery: 'Bugün kendine alan aç.', journal: 'Kendine bir cümle.', insights: 'Bedeninin küçük ipuçları.', pro: 'Ritim Pro ile keşfet.', method: 'Doğallık, dengeden önce.' };
export default function Panels({ panel, onClose }: { panel: Exclude<Panel, 'capture' | null>; onClose: () => void }) {
  return <Sheet title={TITLES[panel]} onClose={onClose} testID={`${panel}-sheet`}>
    {['sleep', 'recovery', 'journal'].includes(panel) ? <LogEditor kind={panel} onClose={onClose} /> : panel === 'pro' ? <ProEditor onClose={onClose} /> : panel === 'insights' ? <Insights /> : <Method />}
  </Sheet>;
}
function LogEditor({ kind, onClose }: { kind: string; onClose: () => void }) {
  const s = useStyles(); const t = useTypography(); const { colors: c } = useTheme(); const { data, refresh, notify } = useApp();
  const [sleep, setSleep] = useState(String(data?.log.sleep ?? 7.5)); const [journal, setJournal] = useState(data?.log.journal_entry || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const save = async () => {
    Keyboard.dismiss(); const hours = Number(sleep.replace(',', '.'));
    if (kind === 'sleep' && (!sleep.trim() || !Number.isFinite(hours) || hours < 0 || hours > 24)) { setError('0 ile 24 arasında bir uyku süresi gir.'); return; }
    if (kind === 'recovery' && !journal.trim()) { setError('Kendine kısa bir not bırak. Birkaç kelime yeterli.'); return; }
    setBusy(true);
    try { await api('/logs/today', 'PUT', kind === 'sleep' ? { sleep: hours } : { journal_entry: journal.trim(), ...(kind === 'recovery' ? { recovery_mode: true } : {}) }); await refresh(); onClose(); notify(kind === 'recovery' ? 'Ritmin kesilmedi. Bugünün rengi lavanta.' : 'Kaydın güncellendi. Kendine iyi gel.'); }
    catch (e: any) { setError(e.message); } finally { setBusy(false); }
  };
  return <>
    <View style={s.editorHero}><View style={s.editorIcon}><Icon name={kind === 'sleep' ? 'moon-outline' : kind === 'recovery' ? 'pause-outline' : 'create-outline'} size={32} color={c.onInfo} /></View><Text style={t.h2}>{kind === 'sleep' ? 'Bedenin dün gece ne kadar dinlendi?' : kind === 'recovery' ? 'Dinlenmek, vazgeçmek değil.' : 'Bugün neye ihtiyacın var?'}</Text><Text style={t.body}>{kind === 'sleep' ? 'Yaklaşık uyku süren yeterli. Daha iyi anlamak için küçük bir kayıt.' : kind === 'recovery' ? 'Su ve uyku hedeflerine ara verebilirsin. Günlük çizgin boş kalmaz; lavanta rengiyle devam eder.' : 'Bu alan sadece senin. Hislerini birkaç kelimeyle yakala.'}</Text></View>
    {kind === 'sleep' ? <><Field testID="sleep-hours-input" label="Uyku süren (saat)" keyboardType="decimal-pad" value={sleep} onChangeText={setSleep} maxLength={5} /><View style={s.quickHours}>{[5, 6, 7, 8, 9].map(h => <Pressable key={h} testID={`sleep-preset-${h}`} onPress={() => setSleep(String(h))} style={({ pressed }) => [s.hour, Number(sleep) === h && s.selectedHour, pressed && s.pressed]}><Text style={s.hourText}>{h} sa</Text></Pressable>)}</View></> : <Field testID="journal-entry-input" label={kind === 'recovery' ? 'Mikro günlüğün · zorunlu' : 'Mikro günlüğün'} placeholder="Bugün bedenim biraz yavaşlamaya ihtiyaç duyuyor…" multiline value={journal} onChangeText={setJournal} maxLength={1000} />}
    <Info text={error} error /><Button testID={`${kind}-save-button`} title={kind === 'recovery' ? 'Dinlenme modunu başlat' : 'Kaydet'} onPress={save} loading={busy} icon="checkmark" />
    <Text style={t.small}>{kind === 'sleep' ? 'Uyku ihtiyacı kişiden kişiye değişir. 8 saat yalnızca genel takip referansıdır.' : 'Dinlenme günün de yolculuğunun bir parçası.'}</Text>
  </>;
}
function ProEditor({ onClose }: { onClose: () => void }) {
  const s = useStyles(); const t = useTypography(); const { colors: c } = useTheme(); const { user, setUser } = useSession(); const { refresh, notify } = useApp(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const toggle = async () => { setBusy(true); try { const next = await api('/subscription', 'PUT', { tier: user?.subscription === 'pro' ? 'free' : 'pro' }); setUser(next); await refresh(); onClose(); notify(next.subscription === 'pro' ? 'Pro keşfin başladı. Ödeme alınmadı.' : 'Ücretsiz plana geçtin. Kayıtların sende.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  return <><View style={s.proHero}><Icon name="sparkles-outline" size={38} color={c.brandPrimary} /><Text style={s.proTitle}>Kendini biraz{ '\n' }daha yakından tanı.</Text><Text style={t.body}>Daha fazla baskı değil.{ '\n' }Bedenine daha fazla anlayış.</Text></View>{[['camera-outline', 'Sınırsız kamera analizi', 'Günlük kullanım sınırı olmadan keşfet.'], ['git-network-outline', 'Akıllı içgörüler', 'Uyku ve beslenme ilişkilerini gör.'], ['nutrition-outline', 'Mikro besin grafikleri', 'Demir, kalsiyum ve daha fazlası.'], ['color-palette-outline', 'Sana özel temalar', 'Gün ışığı veya Gece bahçesi.']].map(([icon, title, sub]) => <View key={title} style={s.feature}><Icon name={icon as any} size={23} color={c.brandPrimary} /><View style={t.flex}><Text style={t.h3}>{title}</Text><Text style={t.small}>{sub}</Text></View><Icon name="checkmark" size={18} color={c.brandPrimary} /></View>)}<Info text="Bu bir prototip deneme geçişidir. Abonelik satın alınmaz, ödeme veya kart bilgisi istenmez. İstediğin zaman ücretsiz plana dönebilirsin." /><Info text={error} error /><Button testID="subscription-toggle-button" title={user?.subscription === 'pro' ? 'Ücretsiz plana dön' : 'Pro denemesini başlat'} onPress={toggle} loading={busy} /><Text style={t.small}>Temel alışkanlık takibi ve klinik PDF raporu her zaman ücretsiz.</Text></>;
}
function Insights() {
  const s = useStyles(); const t = useTypography(); const { colors: c } = useTheme(); const { data, setPanel } = useApp();
  if (!data?.insight) return <><View style={s.proHero}><Icon name="git-network-outline" size={42} color={c.onInfo} /><Text style={t.h2}>Her şey birbirine bağlı.</Text><Text style={t.body}>Kısa bir gece, tatlı isteğini etkileyebilir. Ritim Pro, kayıtlarındaki olası bağlantıları görünür kılar.</Text></View><Card><Text style={t.h3}>Uyku + beslenme + sen</Text><Text style={t.body}>Yeterli veri olduğunda, uykunun 6 saatten kısa olduğu günlerde 15.00 sonrası öğün başına şeker artışını birlikte değerlendirir.</Text></Card><Button title="Pro özelliklerini dene" testID="insights-pro-button" onPress={() => setPanel('pro')} /><Info text="Bu, bilgilendirici bir korelasyondur; tıbbi tavsiye değildir. Bir neden-sonuç ilişkisini kanıtlamaz." /></>;
  const micros = [{ key: 'iron', name: 'Demir', goal: 18, unit: 'mg' }, { key: 'calcium', name: 'Kalsiyum', goal: 1000, unit: 'mg' }, { key: 'magnesium', name: 'Magnezyum', goal: 375, unit: 'mg' }, { key: 'vitamin_c', name: 'C vitamini', goal: 80, unit: 'mg' }];
  return <><Card style={s.insightHero}><Icon name={data.insight.triggered ? 'bulb-outline' : 'sparkles-outline'} size={30} color={c.onInfo} /><Text testID="insight-title" style={t.h2}>{data.insight.title}</Text><Text testID="insight-message" style={t.body}>{data.insight.message}</Text></Card><Info text={data.insight.disclaimer} /><Text style={t.h2}>Günün mikro besinleri</Text><Text style={t.small}>Kaydedilen örnek öğünlerin toplamı · Genel referanslara oran</Text>{micros.map(m => { const value = data.micronutrients?.[m.key] || 0; return <View testID={`micronutrient-${m.key}`} key={m.key} style={s.nutrient}><View style={t.between}><Text style={t.h3}>{m.name}</Text><Text style={t.small}>{value} / {m.goal} {m.unit}</Text></View><View style={s.track}><View style={[s.bar, { width: `${Math.min(100, value / m.goal * 100)}%` }]} /></View></View>; })}<Info text="Grafikler simüle edilmiş besin değerlerine dayanır. Genel referanslar kişisel ihtiyaç önerisi değildir; takviye veya tedavi kararı için kullanılamaz." /></>;
}
function Method() {
  const s = useStyles(); const t = useTypography();
  return <><Text style={t.body}>Kalori saymak yerine yemeğinin kaynağına, çeşitliliğine ve gününün bütününe bakıyoruz.</Text><Card style={s.method}><Text style={t.eyebrow}>İKİ KATMANLI ÖĞÜN PUANI</Text><Text style={s.methodFormula}>%60 doğallık{ '\n' }+ %40 makro denge</Text><Text style={t.body}>Sonuç: 0–100 arası bir öğün puanı.</Text></Card><Text style={t.h3}>1. FNI · Gıdanın doğallığı</Text><Text style={t.body}>Ev yapımı: 95 · Restoran: 65 · Paketli: 30. Kaynak etiketi başlangıç varsayımıdır; tek başına işlenme düzeyini veya sağlık etkisini belirlemez.</Text><Text style={t.h3}>2. Makro denge</Text><Text style={t.body}>Enerji dağılımında protein %20, karbonhidrat %50, yağ %30 referans alınır. Makro denge: %50 dağılım uyumu, %30 lif (10 g referans), %20 şeker (10 g üzeri azalan puan). Bu, klinik olarak doğrulanmamış bir prototip formülüdür.</Text><Text style={t.h3}>Günlük genel puan</Text><Text style={t.body}>Beslenme %60, uyku %25, su %15. Yalnızca kaydettiğin verilerin ağırlıkları yeniden ölçeklenir. Hiç veri yoksa puan gösterilmez. Dinlenme günleri lavanta rengiyle devam eder.</Text><View style={s.legend}><Text style={t.body}>80–100 · Dengeli bir adım</Text><Text style={t.body}>50–79 · Gelişime açık bir denge</Text><Text style={t.body}>0–49 · Yeni seçimlere alan var</Text></View><Info text="Bu prototipte yapay zekâ tanıma ve makro/mikro besin değerleri simüledir; USDA canlı veri bağlantısı yoktur. Tüm içgörüler bilgilendiricidir, tıbbi tavsiye değildir." /></>;
}
const useStyles = makeStyles(c => ({ editorHero: { gap: 17, paddingBottom: 4 }, editorIcon: { width: 75, height: 75, borderRadius: 27, backgroundColor: c.lavender, alignItems: 'center', justifyContent: 'center' }, quickHours: { flexDirection: 'row', gap: 8 }, hour: { flex: 1, minHeight: 44, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: c.surfaceTertiary, borderWidth: 1, borderColor: c.border }, selectedHour: { backgroundColor: c.mint, borderColor: c.brandPrimary }, hourText: { fontSize: 13, color: c.onSurface }, pressed: { opacity: .6 }, proHero: { backgroundColor: c.mint, borderRadius: 25, padding: 24, gap: 17 }, proTitle: { color: c.onSurface, fontSize: 30, letterSpacing: -1.2, lineHeight: 36, fontWeight: '500' }, feature: { flexDirection: 'row', gap: 14, alignItems: 'center', paddingVertical: 5 }, insightHero: { backgroundColor: c.lavender, borderColor: c.transparent }, nutrient: { gap: 12, paddingVertical: 8 }, track: { height: 9, backgroundColor: c.surfaceTertiary, borderRadius: 7, overflow: 'hidden' }, bar: { height: '100%', backgroundColor: c.success, borderRadius: 7 }, method: { backgroundColor: c.mint }, methodFormula: { fontSize: 29, color: c.onSurface, lineHeight: 37, letterSpacing: -1 }, legend: { backgroundColor: c.peach, borderRadius: 22, padding: 18, gap: 10 } }));