import { useState } from 'react';
import { View, Text, ScrollView, Pressable } from 'react-native';
import { makeStyles, useTheme } from '@/src/theme';
import { useSession } from '@/src/session';
import { useApp } from '@/src/app-context';
import { api, exportReport } from '@/src/api';
import { Button, Card, Icon, Info, useTypography, Sheet } from '@/src/components/ui';

export default function Profile() {
  const s = useStyles(); const t = useTypography(); const { colors: c } = useTheme(); const { user, setUser, logout } = useSession(); const { data, setPanel, notify } = useApp();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false);
  const report = async () => { setBusy(true); try { await exportReport(); notify('Klinik raporun paylaşılmaya hazır.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const theme = async () => { if (user?.subscription !== 'pro') { setPanel('pro'); return; } try { setUser(await api('/theme', 'PUT', { theme: user.theme === 'light' ? 'dark' : 'light' })); } catch (e: any) { setError(e.message); } };
  return <ScrollView testID="profile-scroll" showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
    <View style={s.identity}><View style={s.avatar}><Text style={s.initial}>{user?.name[0]?.toLocaleUpperCase('tr-TR')}</Text><View style={s.leaf}><Icon name="leaf" size={14} color={c.brandPrimary} /></View></View><Text testID="profile-name" style={t.h2}>{user?.name}</Text><Text style={t.small}>{user?.email}</Text><View style={s.tier}><Text testID="subscription-status" style={s.tierText}>{user?.subscription === 'pro' ? 'RİTİM PRO · DENEME' : 'RİTİM · ÜCRETSİZ'}</Text></View></View>
    <Card style={s.proCard}><View style={t.between}><View style={t.row}><Icon name="sparkles-outline" /><Text style={t.h2}>Biraz daha derine.</Text></View><Text style={s.proBadge}>PRO</Text></View><Text style={t.body}>Bedeninin bağlantılarını keşfet. Sınırsız analiz, mikro besinler ve sana özel temalar.</Text><Button testID="profile-pro-button" title={user?.subscription === 'pro' ? 'Deneme üyeliğini yönet' : 'Pro özelliklerini dene'} onPress={() => setPanel('pro')} /><Text style={s.note}>Prototip denemesi · Ödeme veya kart bilgisi gerekmez.</Text></Card>
    <Card testID="camera-usage-card"><View style={t.between}><View style={t.row}><Icon name="camera-outline" /><Text style={t.h3}>Bugünkü analizlerin</Text></View><Text style={s.usage}>{data?.camera_used ?? 0}<Text style={t.small}> / {data?.camera_limit ?? '∞'}</Text></Text></View><Text style={t.small}>{user?.subscription === 'pro' ? 'Pro denemesinde kamera kullanımın sınırsız.' : 'Ücretsiz planda günde 5 analiz. Hakların yerel gece yarısında yenilenir.'}</Text></Card>
    <Text style={t.eyebrow}>SANA VE DİYETİSYENİNE</Text>
    <Card><View style={t.row}><View style={s.reportIcon}><Icon name="document-text-outline" color={c.brandPrimary} size={24} /></View><View style={t.flex}><Text style={t.h3}>Klinik PDF raporu</Text><Text style={t.small}>Son 30 günün, tek bir yerde.</Text></View></View><Text style={t.body}>Öğünlerini, uyku ve su kayıtlarını, dinlenme günlerini diyetisyeninle paylaş.</Text><Button testID="export-report-button" title="Raporu indir ve paylaş" icon="share-outline" onPress={report} loading={busy} secondary /><Text style={s.note}>Her zaman ücretsiz. Yalnızca senin kayıtlarınla.</Text></Card>
    <Pressable testID="theme-toggle-button" onPress={theme} style={({ pressed }) => [s.row, pressed && s.pressed]}><Icon name={user?.theme === 'dark' ? 'sunny-outline' : 'moon-outline'} /><View style={t.flex}><Text style={t.h3}>Görünüm</Text><Text style={t.small}>{user?.theme === 'dark' ? 'Gece bahçesi' : 'Gün ışığı'} · Pro temaları</Text></View><Icon name="chevron-forward" size={18} /></Pressable>
    <Pressable testID="profile-method-button" onPress={() => setPanel('method')} style={({ pressed }) => [s.row, pressed && s.pressed]}><Icon name="leaf-outline" /><View style={t.flex}><Text style={t.h3}>Ritim yaklaşımı</Text><Text style={t.small}>Puanlar, doğallık ve şeffaflık</Text></View><Icon name="chevron-forward" size={18} /></Pressable>
    <Info text={error} error /><Button testID="logout-button" title="Çıkış yap" onPress={() => setConfirm(true)} secondary />
    <Text style={s.footer}>ritim.  ·  Kendine iyi gel.{ '\n' }Prototip 1.0 · Besin analizi örnek veridir.</Text>
    {confirm && <Sheet title="Görüşmek üzere." testID="logout-confirm-sheet" onClose={() => setConfirm(false)}><Text style={t.body}>Kayıtların hesabında saklı kalır. İstediğin zaman kendi ritminde geri dönebilirsin.</Text><Button testID="logout-confirm-button" title="Çıkış yap" onPress={async () => { try { await logout(); } catch { /* Local logout still completes. */ } }} /><Button testID="logout-cancel-button" title="Burada kal" onPress={() => setConfirm(false)} secondary /></Sheet>}
  </ScrollView>;
}
const useStyles = makeStyles(c => ({ content: { paddingHorizontal: 24, paddingTop: 4, paddingBottom: 30, gap: 22, maxWidth: 680, width: '100%', alignSelf: 'center' }, identity: { alignItems: 'center', gap: 9, paddingVertical: 12 }, avatar: { width: 76, height: 76, borderRadius: 30, backgroundColor: c.brandSecondary, alignItems: 'center', justifyContent: 'center', marginBottom: 6 }, initial: { fontSize: 34, color: c.brandPrimary, fontWeight: '400' }, leaf: { backgroundColor: c.surfaceSecondary, width: 28, height: 28, borderRadius: 15, position: 'absolute', right: -5, bottom: -3, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: c.border }, tier: { backgroundColor: c.surfaceTertiary, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 8, marginTop: 4 }, tierText: { fontSize: 9, color: c.onSurfaceTertiary, letterSpacing: 1.2 }, proCard: { backgroundColor: c.mint, borderColor: c.transparent }, proBadge: { fontSize: 9, color: c.brandPrimary, fontWeight: '600', letterSpacing: 1.4 }, note: { fontSize: 10, color: c.muted, textAlign: 'center', lineHeight: 16 }, usage: { fontSize: 26, color: c.onSurface }, reportIcon: { width: 50, height: 50, borderRadius: 18, backgroundColor: c.mint, alignItems: 'center', justifyContent: 'center' }, row: { flexDirection: 'row', gap: 16, alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderColor: c.border }, pressed: { opacity: .6 }, footer: { color: c.muted, fontSize: 11, textAlign: 'center', lineHeight: 21 } }));